#ifndef IZIAVRUTILS_H_
#define IZIAVRUTILS_H_

#include <iziAvr.h>

#ifdef __cplusplus
extern "C" {
#endif

/** \struct SIziDate
 * Structure representing system date.
 */
struct SIziCompilationDate
{
	uint16_t 	year;
	uint8_t		month;
	uint8_t		day;
};
typedef struct SIziCompilationDate TIziCompilationDate;

/** \struct SIziKernelVersion
 *	Structure containing version of used library.
 *	\
 */
struct SIziKernelVersion
{
	/** Major version of library. This number is arbitrarily determined
		in build configuration. */
	uint8_t 	majorVersion;
	/**	Minor version is a build number generated by build engine */
	uint16_t	minorVersion;
};
typedef struct SIziKernelVersion TIziKernelVersion;



#ifdef __cplusplus
}
#endif

#endif /* IZIAVRUTILS_H_ */
